urbanairship/ua-unity-plugin

android-plugin-lib/src/main/AndroidManifest.xml, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/IntentReceiver.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityAutopilot.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UrbanAirshipApplication.java
Encapsulate all of takeoff in an autopilot class to make it easier to call takeoff in apps that cant use our application.
=> [MB-1670] Use autopilot to call takeoff

Assets/Plugins/iOS/UAUnityPlugin.m
Action operators to the rescue.
The main deal here is just to make sure that if someone sends one of these things to a unity game it doesn't cover up the screen while the game is running. This replaces the respective actions with modified versions that "pause the game". Really what it does is trigger the OnApplicationPause event, so the game can pause itself the way it's designed to.
=> [MB-1674] Pause app before displaying inbox or landing pages

Assets/Plugins/Android/AndroidManifest.xml
Updates the default manifest to what Unity 5.3 provides
=> [MB-1678] Update base AndroidManifest.xml to Unity 5.3 version

docs/.gitignore, docs/Doxyfile, docs/build.gradle, docs/mainpage.md, docs/theme/customdoxygen.css, docs/theme/doxy-boot.js, docs/theme/doxygen-bootstrap_LICENSE, docs/theme/footer.html, docs/theme/header.html, settings.gradle
Generates docs using doxygen.
Make sure doxygen is installed then run:
```  
./gradlew build
open docs/build/html/index.html
```
=> [MB-1673] Generate API docs

Assets/Scripts/UrbanAirship.cs, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs
Just trying to make the plugin interface more palatable to the .NET world. This means rewriting things to use properties where possible (instead of argless setters and getters), and trying to adopt some consistent style guidelines. FWIW MonoDevelop has its own style guide derived from Mono, which explains some of the odd seeming choices the editor makes for you by default 
http://www.mono-project.com/community/contributing/coding-guidelines/
=> [MB-1598] update interface with properties, monodevelop style

Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityAutopilot.java, android-plugin-lib/src/main/res/values/attrs.xml
Adds log level options to the setting editor
=> [MB-1687] Add log level settings

Assets/UrbanAirship/Editor/UAAssetPostprocessor.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, Assets/UrbanAirship/Editor/UAMenu.cs, Assets/UrbanAirship/PluginInfo.cs, build.gradle
Menu:
About dialog:
Docs menu items open urls in the default browser. The API Docs are not uploaded yet so it will 404.
=> MB-1684: Add about and docs menu items

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/TagGroupEditor.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Testing: needs it.
```
UAirship.EditNamedUserTagGroups ()
.AddTag ("what", "hi")
.RemoveTag ("ok", "cool")
.Apply ();
```
=> MB-1466: Tag Group support

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Creates a static game object to listen for received pushes. Now we can deserialize the payload into a push object before listeners are notified.
=> [MB-1699] Fix OnPushReceived listener

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Changes: 
- BackgroundLocationEnabled => BackgroundLocationAllowed
- PushEnabled => UserNotificationsEnabled
- replaced enabled/disabled methods with a parametrized method
- added a stubbed plugin to avoid doing plugin null checks
- use stubbed plugin if running in the editor
=> [MB-1700] Update interface

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Platforms/UAirship.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/IntentReceiver.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Adds channel registration event. Seems to be an event some apps care about.
=> [MB-1702] Add channel registration event

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Platforms/CustomEvent.cs, Assets/UrbanAirship/Platforms/PushMessage.cs, Assets/UrbanAirship/Platforms/TagGroupEditor.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/PluginInfo.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/IntentReceiver.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
=> [MB-1681]  API docs

Assets/Plugins/iOS/UAUnityPlugin.m
This allows log messages to be turned off through our config editor window
=> [MB-1704] Use UA_LDEBUG for iOS logging

Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Platforms/UAirship.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityAutopilot.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Fires an event when a deep link is received.
Testing:
* Android log
I/Unity: Received deep link: http://www.google.com
UrbanAirshipBehaviour:OnDeepLinkReceived(String)
UrbanAirship.UrbanAirshipListener:OnDeepLinkReceived(String)
* iOS log
Received deep link: http://www.google.com
UrbanAirshipBehaviour:OnDeepLinkReceived(String)
UrbanAirship.DeepLinkReceivedEventHandler:Invoke(String)
UrbanAirship.UrbanAirshipListener:OnDeepLinkReceived(String)
=> [MB-1983] Fire an event when a deep link is received.

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Editor/UAAssetPostprocessor.cs, Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, Assets/UrbanAirship/Editor/UADependencies.cs, Assets/UrbanAirship/Editor/UAMenu.cs, Assets/UrbanAirship/Editor/UAPostBuild.cs, Assets/UrbanAirship/Editor/UAUtils.cs, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/CustomEvent.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/JsonArray.cs, Assets/UrbanAirship/Platforms/PushMessage.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/TagGroupEditor.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, Assets/UrbanAirship/PluginInfo.cs, CHANGELOG, COPYING, airship.properties, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/CustomMessageActivity.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/CustomMessageCenterActivity.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityAirshipReceiver.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityAutopilot.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Unity's JSON cant handle a Dictionary so we have to work around this by passing model objects back and forth. PushMessage expects an Array of Extra. An Extra is defined by { string key, string value}. So we need to format the json to be something like:
```
"extras": [ {"key": "some key", "value": "some value" }, ...]
```
=> Release 3.2.2

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Adds a method for retrieving the number of unread messages for the message center.
=> [MB-2092] Add Method For Retrieving Unread Message Count

CHANGELOG, airship.properties
=> Release 3.3.0

Assets/UrbanAirship/Editor/UADependencies.xml, CHANGELOG.md, airship.properties
Changes:
- Fixed resolving the unity plugin lib for Android
- Bumped Android UA SDK to 8.9.3
=> Release 4.3.2

Assets/UrbanAirship/PluginInfo.cs
=> Fixing typos

Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Platforms/UAirship.cs, CHANGELOG.md, airship.properties, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Added support for OnPushOpened in the listener.
=> Added support for OnPushOpened in the listener

CHANGELOG.md, airship.properties
Release 5.1.0. Updates dependencies.
=> Release 5.1.0

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Editor/GoogleJson.cs, Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, Assets/UrbanAirship/Editor/UAMenu.cs, Assets/UrbanAirship/Editor/UAPostBuild.cs, Assets/UrbanAirship/Editor/UAPreBuild.cs, Assets/UrbanAirship/Editor/UAUpdater.cs, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/CustomEvent.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/JsonArray.cs, Assets/UrbanAirship/Platforms/PushMessage.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/TagGroupEditor.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, Assets/UrbanAirship/PluginInfo.cs, COPYING
=> [MOBILE-462] update copyrights

CHANGELOG.md, airship.properties
=> Release 6.0.1

README.md
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your pull request is reviewed as quickly and efficiently as possible.
ℹ Updates the set up instructions for Unity on android
ℹ Making the build process easier for android.
ℹ I built and tested push on android following the set up instructions provided.
=> Updated Unity readme to help improve setting up Android

CHANGELOG.md, airship.properties
=> Release 6.0.2

airship.properties, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, unity-plugin/build.gradle, unity-plugin/src/main/java/com/urbanairship/unityplugin/PluginLogger.java, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityAutopilot.java, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Update our plugin's Android SDK to 12.2.0
New features in 12.2.0
Local builds of an empty Unity app with our plugin. Was able to set a tag and receive a push.
There are 4 commits that align with the steps I went through to upgrade the SDK. It might be worth reviewing commit by commit.
=> [MOBILE-1047] Update Android to 12.2.0

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Add in-app methods to Unity
Customer request.
Used the behavior script to set and read values on both iOS and Android.
=> [MOBILE-1364] Add inapp methods

Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Editor/UAPostBuild.cs, unity-plugin/build.gradle, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityAutopilot.java
Registers the Unity plugin version in analytics. I manually verified it works like you do.
=> [MOBILE-1366] Register unity plugin version

CHANGELOG.md, airship.properties
=> Release 7.0.0

CHANGELOG.md, airship.properties
=> Release 7.0.1

README.md
Updates README to be in sync with current plugin and branding.
=> [MOBILE-543] Update README

Assets/Plugins/iOS/UAUnityPlugin.m, airship.properties
Updates the iOS SDK version to 13.3.2.
=> [MOBILE-1571] Update iOS to 13.3.2

Assets/UrbanAirship/Editor/UADependencies.xml, airship.properties, unity-plugin/build.gradle, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityAutopilot.java, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Update to Android SDK 13.1.2. 
Use new Android packages: automation, location and message center.
call:
`./gradlew build` to build package then create sample app unity to test it.
=> [Mobile 1570] - Update Android SDK to 13.1.2

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Add support for named user attributes.
Feature support on Unity.
=> [MOBILE-1568] Named user attributes support

CHANGELOG.md, airship.properties
Update Android and iOS SDK
Update our Unity module
Build and check channel ID
=> Release 8.1.0

Assets/Plugins/iOS/UAUnityMessageViewController.h, Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, Assets/UrbanAirship/Editor/UADependencies.xml, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, Assets/UrbanAirship/Tests/MessageCenterTests.cs, CHANGELOG.md, airship.properties, build.gradle, unity-plugin/build.gradle, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Update to latest SDKs versions
Add preference center
Remove location
Add the Privacy manager methods
To keep the SDK updated
Edited the UrbanAirship behaviour script launched at start and called all the methods, verifying that everything is run correctly
=> [MOBILE-2533] Update Unity to latest SDKs

CHANGELOG.md, airship.properties
Prepare for release 9.0.1, to fix the iOS build error
=> Release 9.0.1

CHANGELOG.md, airship.properties
Update Unity to the latest SDKs
To stay updated
By running the sample app on Android & iOS
=> [MOBILE-3159] Update to Android 16.7.1 & iOS 16.9.2
