build.gradle
Seems the exportPackage triggers PlayServicesResolver  which causes android dependencies to be staged and packaged.
=> [MB-1680] Be explicit about what packages to export

Assets/UrbanAirship/Editor/UAAssetPostprocessor.cs, Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityAutopilot.java, android-plugin-lib/src/main/res/values/attrs.xml
Changes:
- Android is now configured through xml file
- Added notification icon and accent color config options
- Fixed GCM sender not saving
- Cleaned up the config editor
Testing - set red alert icon through unity:
=> [MB-1471] Add config for notification icon and color.

Assets/UrbanAirship/Platforms/UAirship.cs
Unity does have a JSON library, albeit a limited one. It's not possible to do arbitrary JSON object manipulation – you have to create classes or structs marked serializable and the appropriate fields will be filled out (or not).
Some fussy details:
* If the JSON string doesn't exactly match the model JsonUtility is working with, missing fields will just be left empty/null on the resulting model object. We need to be careful to make sure fields are non-null when deserializing
* JsonUtility does appear to throw exceptions if the input string is either malformed or null. Since this would be our (as opposed to the customer's) mistake, and since these script exceptions don't appear to crash the game, it's probably in our best interest to let them be thrown so that customers are more likely to …
=> [MB-1676] proper serialization

Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Platforms/CustomEvent.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/JsonArray.cs, Assets/UrbanAirship/Platforms/PushMessage.cs, Assets/UrbanAirship/Platforms/UAirship.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
"Full" push payload support. The only caveat here is that, once again largely due to the decrepitude of JsonUtility, we're not fully deserializing extras. This is essentially the same situation as on Android, where extras are <string, string> and arbitrarily encoded non-string values are still presented as strings. That should be enough, though.
todo: Android native plugin implementation
=> [MB-1671] full push payload support

android-plugin-lib/build.gradle, android-plugin-lib/src/main/AndroidManifest.xml, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/CustomMessageActivity.java, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/CustomMessageCenterActivity.java, android-plugin-lib/src/main/res/values-v14/style.xml
The default unity theme is full screen no action bar, this sets a default action bar theme to the message center activities. I am unable to override the manifest entries so I had to create new activities that I could add to the manifest.
=> [MB-1701] Theme the message center

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, android-plugin-lib/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Added `AssociateIdentifier` method to set custom identifiers.
Testing:
UAirship.Shared.AssociateIdentifier ("ice", "cream");
UAirship.Shared.AssociateIdentifier ("friend", "ship");
UAirship.Shared.AssociateIdentifier (null, "ship"); // invalid null key
UAirship.Shared.AssociateIdentifier ("friend", null); // removes identifier for key 'friend'
// android
UALib: UnityPlugin associateIdentifier with identifier: cream for key: ice
UALib: PreferenceDataStore - Saving preference: com.urbanairship.analytics.ASSOCIATED_IDENTIFIERS value: {"ice":"cream"}
UALib: Analytics - Adding event: associate_identifiers
UALib: UnityPlugin associateIdentifier with identifier: ship for key: friend
UALib: PreferenceDataStore - Saving preference: com.urbanairship.analytics.ASSOCIATED_IDENTIFIERS value: …
=> [MB-1982] Add support for associated identifiers.

Assets/Plugins/iOS/UAUnityPlugin.m, Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs
Added iOS foreground presentation support through the config.
Default foreground presentation options for iOS 10+ is available via `Window > Urban Airship > Settings`.
The generated `AirshipConfig.plist` will contain the saved settings from above ^ as a customConfig
Testing:
* Receieved push notification with alert, badge & sound while app is in foreground on iOS 10.0.2 iPod.
=> [MB-1975] Added iOS foreground presentation support.

README.md
Update README with link to unity docs for iOS service extension.
Note: Wait for unity docs PR merged & deployed before merging this in.
=> [MB-1972] Update README with link to unity docs for iOS service extension.

Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAPostBuild.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs
Makes it so the plugin does not require installation of the iOS platform. For the config regeneration stuff, I tested:
1. Settings changes that occur while Android is the build target are picked up upon switching platforms to iOS (and vice versa)
2. If a config doesn't exist, switching to that platform will automatically generate the config.
=> [CE-2614] Remove iOS build requirement

Assets/UrbanAirship/Editor/UADependencies.cs, CHANGELOG, airship.properties
Note: we are currently unable to bump the play services or the support library, because the jar resolver doesn't pull those dependencies yet.
=> Release 4.2.0

Assets/UrbanAirship/Platforms/CustomEvent.cs, Assets/UrbanAirship/Platforms/PushMessage.cs, Assets/UrbanAirship/Platforms/TagGroupEditor.cs, Assets/UrbanAirship/Platforms/UAirship.cs
Fixes some warnings around our JSON encoding/decoding work arounds. The UAListener pointed to the component we added, but the field was never used. Seems ok to delete. AddComponent stores a reference the object.
=> [MB-2418] Fix plugin warnings

Assets/UrbanAirship/Editor/UAPostBuild.cs
Checks for the existence of background modes and remote data before adding anything.
=> [MB-2422] Fix replacing UIBackgroundModes in the plist every build

Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs
When the config is loaded it will auto migrate the gcm to prod and dev.
=> [MB-2421] Expose prod and dev FCM sender ID settings

unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Fix tag group tags having quotes around them on Android. Fix was to use the `getString()` instead of `toString()`.
=> [CUSTENG-104] Fix Android tag group issue

Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, Assets/UrbanAirship/Editor/UAUpdater.cs
Fix migration to new version of the plugin for iOS projects. The upgrade process now completes without errors:
1. Download new version of the plugin (urbanairship-X.Y.Z.unitypackage) from bintray.
2. Open existing project in Unity
3. In Unity:
1. Upgrade to new plugin (As of Unity 2019.1.1f1: "Assets" → "Import Package" → "Custom Package")
1. Build and Run (As of Unity 2019.1.1f1: "File" → "Build Settings")
1. If necessary, switch to iOS Platform
1. Build and Run
1. _Unity launches Xcode_
8. In Xcode:
1. if necessary, select a development team.
9. Run
Developers have reported issues upgrading to new versions of our plugin. 
Lots of upgrades of the ua-sample-game project
* There was existing migration code. It was just not up-to-date.
* New migration code used existing patterns, or …
=> [MOBILE-522-iOS] Unity: Clean up cruft in “clean” step

airship.properties
Updates unity jar resolver to 1.2.123. We can switch to tags now but that required more work than just pointing to the sha. Ill create a ticket to do that in the future.
=> Update jar resolver to 1.2.123

Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, CHANGELOG.md, airship.properties
Adds support for EU cloudsite and updates to latest patch versions of the SDK.
Customer request.
Verified the cloud site was being properly set for both iOS and Android.
=> Release 6.2.0

Assets/Plugins/Android/urbanairship-resources/AndroidManifest.xml
Currently running into an issue that resembles this one:
https://github.com/urbanairship/ua-unity-plugin/issues/91
Removes the minSdk and targetSdk version from the urbanairship resources manifest.
Set up a test project, installed the plugin, exported the android project, got the project syncing properly without the warning.
=> [CE-2080] resolve gradle sync error and get android building

Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Add screen tracking to unity.
To add screen tracking to unity and reach functional parity with other plugins.
Ran the sample with the unity sample script with onStart screen tracking added. Ensured breakpoint at trackScreen was hit on start when main camera was tracked.
=> [MOBILE-1330] add screen tracking to unity

airship.properties, build.gradle
Looks up the unity classes.jar in the proper place, and forces our script to use the specified version of unity in the airship.properties file.
=> [MOBILE-1367] Fix unity classes.jar detection

Assets/Plugins/iOS/UAUnityPlugin.h, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Editor/UAConfig.cs, Assets/UrbanAirship/Editor/UAConfigEditor.cs, Assets/UrbanAirship/Platforms/Android/UAirshipPluginAndroid.cs, Assets/UrbanAirship/Platforms/IUAirshipPlugin.cs, Assets/UrbanAirship/Platforms/StubbedPlugin.cs, Assets/UrbanAirship/Platforms/UAirship.cs, Assets/UrbanAirship/Platforms/iOS/UAirshipPluginIOS.cs, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Add data collection enabled flag to Unity
to support data collection feature
I manually tested both iOS and Android
=> [Mobile 1331]  Add data collection enabled flag to Unity

.github/CODEOWNERS, Assets/Plugins/iOS/UAUnityPlugin.m, Assets/Scripts/UrbanAirshipBehaviour.cs, Assets/UrbanAirship/Platforms/AttributeEditor.cs, unity-plugin/src/main/java/com/urbanairship/unityplugin/UnityPlugin.java
Add date attribute support to our Unity plugin.
We want to provide full attribute support to our Unity customers.
Built new sample apps and tested that date (and other) attributes were set correctly.
=> [MOBILE-1569] Add date attributes

Assets/Plugins/iOS/UAUnityPlugin.m, CHANGELOG.md, airship.properties
The iOS plugin is using the wrong selector for the channel updated event, which leads to an unrecognized selector crash. See: https://github.com/urbanairship/ua-unity-plugin/issues/122
This warrants a patch, since it will crash any iOS Unity app that does any CRA work beyond channel creation.
~Note: I haven't tested this yet since my Unity environment is extremely out of date. If anyone wants to help verify I'd appreciate it.~
Building and running fine locally for me now, and independently verified by ryan
=> MOBILE-1930 Unity plugin 8.0.1

.github/workflows/release.yaml
Updates to the new modular GCP setup action.
So that deploys continue working.
Doing it live, but tested the new action in a private repo and it installed the GCP CLI utils without issue.
=> [MOBILE-2438] Update setup-cloud action in release workflow

Assets/Plugins/iOS/UAUnityPlugin.m
Rename methods names on UAUnityPlugin.m, for _isFeatureEnabled_ and _isAnyFeatureEnabled_, so they match their names in the .h file
To allow the customer to use these methods
=> [MOBILE-2888] Fix typo error

Assets/Plugins/iOS/UAUnityPlugin.m, CHANGELOG.md, airship.properties
Following MOBILE-2960, a crash happens when you register and the channel ID is null
Add a check to avoid Unity crash
To avoid crash
Run the app, check that no crash occurs at first, second, and other launches, when you register or not to pushes
=> [MOBILE-2960] Fix crash and prepare release 9.0.2

Assets/Plugins/iOS/UAUnityPlugin.m, CHANGELOG.md, airship.properties
Fix a crash when the channel ID is null
To fix a crash when channelID is null, requested by a customer : https://urbanairship.atlassian.net/jira/software/c/projects/MOBILE/boards/12?modal=detail&selectedIssue=MOBILE-2960
Uninstall the app, installed it and check that after first launch, registering to push, it doesn't crash
=> [MOBILE-2960] Patch 9.0.3

Assets/Plugins/iOS/UAUnityPlugin.h, CHANGELOG.md, airship.properties
Update Unity plugin version to 9.1.0, Android SDK to 16.4.0 and iOS version to 16.6.0
To keep the plugins updated
By running a sample app embedding the new plugin
=> [MOBILE-3077] Update Unity Plugin 9.1.0

.github/workflows/ci.yaml, .github/workflows/release.yaml, Assets/UrbanAirship/Platforms/AttributeEditor.cs, Assets/UrbanAirship/Platforms/CustomEvent.cs, CHANGELOG.md, airship.properties
- Changed several usages of `ToString()` to `ToString(CultureInfo.InvariantCulture)` to avoid the possibility of formatting with a comma as the decimal separator.
- Bumped to version 9.2.1
- Updated changelog
Customer reported issue
Imported the package into an empty sample app, set up credentials, and added the sample behavior to a game object, then ran on device with the language set to French. I was able to reproduce the issue and confirm that it no longer happens with this fix.
=> [MOBILE-4122] Release 9.2.1
